package ifi.p20.gl.entity;
// Generated Sep 11, 2016 4:01:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Request generated by hbm2java
 */
@Entity
@Table(name = "request", catalog = "carnet_location")
public class Request implements java.io.Serializable {

	private Integer id;
	private String country;
	private String city;
	private User user;
	private String name;
	private float price;
	private float area;
	private int number_of_parts;
	private String street;
	private String description;
	private Date date;
	private int status;

	public Request() {
	}

	public Request(String city, User user, String name, float price, float area, Date date, int status) {
		this.city = city;
		this.user = user;
		this.name = name;
		this.price = price;
		this.area = area;
		this.date = date;
		this.status = status;
	}

	public Request(String country, String city, User user, String name, float price, float area, String street, String description,
			Date date, int status) {
		this.country = country;
		this.city = city;
		this.user = user;
		this.name = name;
		this.price = price;
		this.area = area;
		this.street = street;
		this.description = description;
		this.date = date;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "country", nullable = false)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}


	@Column(name = "city", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "area", nullable = false, precision = 12, scale = 0)
	public float getArea() {
		return this.area;
	}

	public void setArea(float area) {
		this.area = area;
	}

	@Column(name = "street", length = 250)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "number_of_parts", nullable = false)
	public int getNumber_of_parts() {
		return number_of_parts;
	}

	public void setNumber_of_parts(int number_of_parts) {
		this.number_of_parts = number_of_parts;
	}

}
