package ifi.p20.gl.entity;
// Generated Sep 11, 2016 4:01:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "carnet_location")
public class User implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private boolean active;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Offer> offers = new HashSet<Offer>(0);
	private Set<Message> messagesForIdUser2 = new HashSet<Message>(0);
	private Set<Request> requests = new HashSet<Request>(0);
	private Set<Message> messagesForIdUser1 = new HashSet<Message>(0);
	private Set<OfferFavorite> offerFavorites = new HashSet<OfferFavorite>(0);
	private Set<Profile> profiles = new HashSet<Profile>(0);

	public User() {
	}

	public User(String email, String password, boolean active) {
		this.email = email;
		this.password = password;
		this.active = active;
	}

	public User(String email, String password, boolean active, Set<Comment> comments, Set<Offer> offers,
			Set<Message> messagesForIdUser2, Set<Request> requests, Set<Message> messagesForIdUser1,
			Set<OfferFavorite> offerFavorites, Set<Profile> profiles) {
		this.email = email;
		this.password = password;
		this.active = active;
		this.comments = comments;
		this.offers = offers;
		this.messagesForIdUser2 = messagesForIdUser2;
		this.requests = requests;
		this.messagesForIdUser1 = messagesForIdUser1;
		this.offerFavorites = offerFavorites;
		this.profiles = profiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 100, unique = true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Offer> getOffers() {
		return this.offers;
	}

	public void setOffers(Set<Offer> offers) {
		this.offers = offers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByIdUser2")
	public Set<Message> getMessagesForIdUser2() {
		return this.messagesForIdUser2;
	}

	public void setMessagesForIdUser2(Set<Message> messagesForIdUser2) {
		this.messagesForIdUser2 = messagesForIdUser2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Request> getRequests() {
		return this.requests;
	}

	public void setRequests(Set<Request> requests) {
		this.requests = requests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByIdUser1")
	public Set<Message> getMessagesForIdUser1() {
		return this.messagesForIdUser1;
	}

	public void setMessagesForIdUser1(Set<Message> messagesForIdUser1) {
		this.messagesForIdUser1 = messagesForIdUser1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<OfferFavorite> getOfferFavorites() {
		return this.offerFavorites;
	}

	public void setOfferFavorites(Set<OfferFavorite> offerFavorites) {
		this.offerFavorites = offerFavorites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

}
